### ISSUE TITLE
What about Chirpstack?

### ISSUE THREAD

**Issue by rcooke** [mcicolella/awesome-lora-lorawan#2]
I'm looking for a LoraWan solution for an isolated network of temperature sensors.  No internet.

In testing I have found that many COTS sensors "need" access to LoraWan server to keep their session keys current.

So it seems I must run something just for that.  And with any luck, getting data out of the system and into my application will be easier.

I'm looking at what you list, but I dont see any mention of Chirpstack.  

https://www.chirpstack.io/

https://www.chirpstack.io/project/

**Comment by rcooke** [comment]
Aha!  I see what has happened.  In your list, under servers, you have:

[LoRa Server](https://www.loraserver.io/) - Open-source LoRaWAN network-server.

Which lnks to page https://www.loraserver.io/

And that now redirects to ChirpStack!

**Comment by mcicolella** [comment]
Updated link!! Thanks for reporting
